/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Latian3;

/**
 *
 * @author SMK TELKOM
 */
public class Latian3 extends javax.swing.JFrame {

    /**
     * Creates new form Latian3
     */
    public Latian3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Panjang = new javax.swing.JTextField();
        Lebar = new javax.swing.JTextField();
        Tinggi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        Sisi = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Jari = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 154, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Balok", jPanel2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel2.setText("Masukkan Panjang : ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(18, 28, 110, 20);

        jLabel3.setText("Masukkan Lebar : ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 60, 100, 20);

        jLabel4.setText("Masukkan Tinggi : ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 90, 110, 20);
        jPanel1.add(Panjang);
        Panjang.setBounds(140, 30, 100, 20);
        jPanel1.add(Lebar);
        Lebar.setBounds(140, 60, 100, 20);
        jPanel1.add(Tinggi);
        Tinggi.setBounds(140, 90, 100, 20);

        jLabel5.setText("cm");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(250, 30, 34, 20);

        jLabel6.setText("cm");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(250, 60, 13, 20);

        jLabel7.setText("cm");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(250, 90, 13, 20);

        jButton1.setText("Hitung");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(110, 130, 63, 23);

        jTabbedPane1.addTab("Balok", jPanel1);

        jPanel4.setLayout(null);

        jLabel10.setText("Masukkan Panjang Sisi");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(27, 30, 140, 14);
        jPanel4.add(Sisi);
        Sisi.setBounds(30, 50, 70, 30);

        jLabel11.setText("cm");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(110, 54, 13, 20);

        jButton3.setText("Volume");
        jPanel4.add(jButton3);
        jButton3.setBounds(40, 100, 67, 23);

        jTabbedPane1.addTab("Bola", jPanel4);

        jPanel3.setLayout(null);

        jLabel8.setText("Masukkan Panjang Jari-Jari");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(27, 30, 140, 14);

        jLabel9.setText("cm");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(110, 54, 13, 20);
        jPanel3.add(Jari);
        Jari.setBounds(30, 50, 70, 30);

        jButton2.setText("Volume");
        jPanel3.add(jButton2);
        jButton2.setBounds(40, 100, 67, 23);

        jTabbedPane1.addTab("Kubus", jPanel3);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(40, 60, 340, 210);

        jLabel1.setText("Program Pencari Volume Bangun Ruang");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 30, 220, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int panjang, lebar, tinggi;
        panjang = Integer.parseInt(Panjang.getText());
        lebar = Integer.parseInt(Lebar.getText());
        tinggi = Integer.parseInt(Tinggi.getText());
        
        int hasil = panjang * lebar * tinggi ;
        try{
            JOptionPane.showMessageDialog(null,"Volume Balok Adalah :"+hasil,"luas",
                    JOptionPane.INFORMATION_MESSAGE);
        } 
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latian3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latian3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latian3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latian3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Latian3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Jari;
    private javax.swing.JTextField Lebar;
    private javax.swing.JTextField Panjang;
    private javax.swing.JTextField Sisi;
    private javax.swing.JTextField Tinggi;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    // End of variables declaration//GEN-END:variables
}
